### ISSUE TITLE
win32_product

### ISSUE THREAD

**Issue by ghost** [WiredPulse/PoSh-R2#1]
Hi,

Really great script, thank you. I was checking it out and noticed it is using win32_product to query installed software information.

This can sometimes cause issues in an environment.
https://gregramsey.net/2012/02/20/win32_product-is-evil/

**Comment by WiredPulse** [comment]
I will put a reference to that link in the script. At the moment, it is the best option from a WMI standpoint even with the potential concerns. Thanks
